# breeding-requirement - Input a positive number
breeding-requirement: 1
# glow-color - Enter a glow color
# Available Colors: AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_PURPLE, DARK_RED, GOLD, GRAY, GREEN, LIGHT_PURPLE, MAGIC, RED, WHITE, YELLOW
glow-color: DARK_RED
# food-requirement - Enter each food required for breeding separated by commas. Leave empty for no additional food
# Available Food: STICK, WOOD,
food-requirement:
  pig:
  cow:
  sheep:
  wolf:
  ocelot:
  chicken:
  horse:
  mushroom_cow:
  rabbit: