name: AnimalAppetite
version: ${project.version}
main: io.github.mrbeezwax.animalappetite.AnimalAppetite
api-version: 1.13
authors: [mrbeezwax]
description: Indicate which animals are ready to be bred again and modifies number of food required for breeding